import { test } from 'node:test'
import assert from 'node:assert/strict'
import { cpSync, existsSync, mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { execFileSync } from 'node:child_process'
import { renderArtefact } from '../lib/render.js'
import { createAsset } from '../lib/assets.js'
import { loadDefinition } from '../lib/definition.js'
import { readModule, writeModule } from '../lib/instance.js'

// A minimal real 1x1 red PNG, base64-encoded — small enough to inline, real
// enough to round-trip through the same file-write/render path a genuine
// upload takes. Matches the fixture tests/assets.test.js uses.
const ONE_PX_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='

test('dry-run does not write out/ files', () => {
  execFileSync('rm', ['-rf', 'instances/examples/out'])
  const result = renderArtefact('examples', 'soap', { dryRun: true })
  assert.equal(existsSync(result.docxPath), false)
  assert.equal(existsSync(result.mdPath), false)
})

test('dry-run compiles the template without writing anything, with no HTML-entity escaping', () => {
  const result = renderArtefact('examples', 'soap', { dryRun: true })
  assert.equal(result.dryRun, true)
  assert.match(result.markdown, /# examples: Solution on a Page/)
  assert.match(result.markdown, /- Client-facing self-service \(ContosoSelfService\)/)
  assert.doesNotMatch(result.markdown, /&#39;|&quot;|&amp;/)
})

test('renders a real docx styled from the HLD reference doc', () => {
  const result = renderArtefact('examples', 'soap')
  assert.equal(existsSync(result.docxPath), true)

  const roundTrip = execFileSync('pandoc', ['-f', 'docx', '-t', 'markdown', result.docxPath], {
    encoding: 'utf8',
  })
  assert.match(roundTrip, /Solution on a Page/)
  assert.match(roundTrip, /Client-facing self-service/)

  const documentXml = execFileSync('unzip', ['-p', result.docxPath, 'word/document.xml'], {
    encoding: 'utf8',
  })
  const headingStyles = [...documentXml.matchAll(/w:pStyle w:val="(Heading\d)"/g)].map((m) => m[1])
  assert.ok(headingStyles.includes('Heading1'))
  assert.ok(headingStyles.includes('Heading2'))
  assert.ok(headingStyles.includes('Heading3'))
  assert.ok((documentXml.match(/<w:numPr>/g) ?? []).length > 0, 'expected real list numbering, not flattened text')

  const referenceStyles = execFileSync(
    'unzip',
    ['-p', 'definitions/design/templates/reference.docx', 'word/styles.xml'],
    { encoding: 'utf8' }
  )
  const outputStyles = execFileSync('unzip', ['-p', result.docxPath, 'word/styles.xml'], {
    encoding: 'utf8',
  })
  const fontsOf = (xml) => new Set([...xml.matchAll(/w:ascii="([^"]+)"/g)].map((m) => m[1]))
  const referenceFonts = fontsOf(referenceStyles)
  const outputFonts = fontsOf(outputStyles)
  for (const font of referenceFonts) {
    assert.ok(outputFonts.has(font), `expected ${font} (from the HLD reference doc) in the rendered docx's fonts`)
  }
})

test('suppressed optional sections do not leave runs of blank lines behind', () => {
  const result = renderArtefact('examples', 'hld', { dryRun: true })
  assert.doesNotMatch(result.markdown, /\n{3,}/)
})

test('reference doc defines the paragraph styles pandoc references for list items', () => {
  // The HLD template doesn't itself define "Compact" (pandoc's tight-list
  // style). Word/LibreOffice silently drop a list item's bullet/indent
  // entirely when its w:pStyle points at an undefined style, even though
  // numbering is set directly on the paragraph — build-reference-doc.py
  // merges this (and pandoc's other auxiliary styles) in from pandoc's own
  // default reference doc. If reference.docx is ever regenerated by a
  // plain copy of the HLD source, this catches the regression before the
  // bullets silently vanish again.
  const referenceStyles = execFileSync(
    'unzip',
    ['-p', 'definitions/design/templates/reference.docx', 'word/styles.xml'],
    { encoding: 'utf8' }
  )
  assert.match(referenceStyles, /w:styleId="Compact"/)

  const result = renderArtefact('examples', 'soap')
  const documentXml = execFileSync('unzip', ['-p', result.docxPath, 'word/document.xml'], {
    encoding: 'utf8',
  })
  const outputStyles = execFileSync('unzip', ['-p', result.docxPath, 'word/styles.xml'], {
    encoding: 'utf8',
  })
  const listParagraphStyles = new Set(
    [...documentXml.matchAll(/<w:pPr>(?:(?!<\/w:pPr>).)*?<w:numPr>.*?<w:pStyle w:val="([^"]+)"\/>/gs)].map(
      (m) => m[1]
    )
  )
  for (const styleId of listParagraphStyles) {
    assert.match(outputStyles, new RegExp(`w:styleId="${styleId}"`), `list paragraphs reference an undefined style "${styleId}"`)
  }
})

test('an asset:<id> reference (#80) inserted into a module field compiles into an embedded image at the same paragraph position in the rendered artefact (#81)', () => {
  const instancesDir = mkdtempSync(join(tmpdir(), 'gantry-instances-'))
  try {
    cpSync('instances/examples', join(instancesDir, 'examples'), { recursive: true })
    rmSync(join(instancesDir, 'examples', 'out'), { recursive: true, force: true })

    const pngBytes = Buffer.from(ONE_PX_PNG_BASE64, 'base64')
    const asset = createAsset(
      'examples',
      {
        filename: 'eligibility-flow.png',
        buffer: pngBytes,
        name: 'Eligibility flow',
        source: 'https://draw.io/diagrams/eligibility-flow',
      },
      { instancesDir }
    )

    const definition = loadDefinition('design')
    const context = readModule(definition, 'examples', 'context', { instancesDir })
    writeModule(
      definition,
      'examples',
      'context',
      {
        status: context.status,
        owner: context.owner,
        fields: {
          ...context.fields,
          driver: `${context.fields.driver}\n\n![Eligibility flow](asset:${asset.id})\n`,
        },
      },
      { instancesDir }
    )

    const result = renderArtefact('examples', 'soap', { instancesDir })
    assert.equal(existsSync(result.docxPath), true)

    // The Pandoc render step resolved the asset reference to the real file
    // in assets/, not a broken/literal "asset:<id>" link.
    assert.doesNotMatch(result.markdown, /asset:/)

    // The final rendered artefact contains an embedded image — not merely
    // a hyperlink or literal text — at the correct paragraph position: the
    // round-tripped markdown places it between the business-driver
    // paragraph the reference was appended to and the next heading
    // ("Affected domains"), matching where the reference appears in the
    // source module field.
    const roundTrip = execFileSync('pandoc', ['-f', 'docx', '-t', 'markdown', result.docxPath], {
      encoding: 'utf8',
    })
    const driverIndex = roundTrip.indexOf('Business driver')
    const imageIndex = roundTrip.indexOf('![Eligibility flow]')
    const affectedDomainsIndex = roundTrip.indexOf('Affected domains')
    assert.ok(driverIndex >= 0 && imageIndex >= 0 && affectedDomainsIndex >= 0)
    assert.ok(driverIndex < imageIndex, 'expected the image after the Business driver section')
    assert.ok(imageIndex < affectedDomainsIndex, 'expected the image before the next heading, Affected domains')

    // The embedded image is a real, extractable media file in the docx
    // (not just referenced by a URL), and its bytes match what was
    // uploaded.
    const mediaListing = execFileSync('unzip', ['-l', result.docxPath], { encoding: 'utf8' })
    const mediaFile = mediaListing
      .split('\n')
      .map((line) => line.trim().split(/\s+/).pop())
      .find((name) => name && /^word\/media\/.*\.png$/.test(name) && name !== 'word/media/image1.png')
    assert.ok(mediaFile, 'expected an embedded PNG media file for the inserted asset')
    const extractedBytes = execFileSync('unzip', ['-p', result.docxPath, mediaFile])
    assert.deepEqual(extractedBytes, pngBytes)
  } finally {
    rmSync(instancesDir, { recursive: true, force: true })
  }
})
